config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }

  get '/' => 'homes#top', as: 'root'
  get '/about' => 'homes#about', as: 'about'
  get 'users/mypage' => 'users#mypage', as: 'mypage' do
    get :likes, on: :collection
  end
  get 'users/information/edit' => 'users#edit', as: 'user_edit_information'
  patch 'users/information' => 'users#update', as: 'user_update_information'
  get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  get 'users/:id' => 'users#show', as: 'user'
  get   'contacts'         => 'contacts#index'
  post  'contacts/confirm' => 'contacts#confirm'
  post  'contacts/thanks'  => 'contacts#thanks'
  resources :posts, only: [:new, :create, :show ,:edit, :update,] do
    resource :likes, only: [:create, :destroy]
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :nickname, presence: true, length: {minimum:3}
  validates :birthday, presence: true
  validates :sex, presence: true
  validates :personal_color, presence: true
  validates :skin_quality, presence: true
  validates :email, presence: true, uniqueness: true

  enum sex: { woman: 0, man: 1 }
  enum personal_color: { spring: 0, summer: 1, autumn: 2, winter: 3, unknown: 4 }
  enum skin_quality: { normal: 0, dry: 1, oily: 2, mixed: 3, notclear: 4 }

  def self.find_omniauth(auth)
    User.where(provider: auth.provider, uid: auth.uid).first
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.twitter_data"]
        user.uid = data["uid"],
        user.provider = data["provider"],
        user.email = "#{Time.now.strftime('%Y%m%d%H%M%S').to_i}-#{user.uid}-#{user.provider}@example.com",
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/22623694.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def age(today = Date.today)
    ((today.to_time - birthday.to_time) / 1.year.seconds).floor
  end

  scope :search, -> (search_params) do      #scopeでsearchメソッドを定義。(search_params)は引数
    return if search_params.blank?          #検索フォームに値がなければ以下の手順は行わない

    personal_color(search_params[:personal_color]).skin_quality(search_params[:skin_quality])
    .keyword1(search_params[:keyword1]).range(search_params[:range]) #下記で定義しているscopeメソッドの呼び出し。「.」で繋げている
  end

  scope :personal_color, -> (personal_color) { where('personal_color like?', personal_color) if personal_color.present? }  #scopeを定義。
  scope :skin_quality, -> (skin_quality) { where('skin_quality like?', skin_quality) if skin_quality.present? }
  scope :keyword1, -> (keyword1) { where("nickname like? OR personal_color like? OR skin_quality like?","%#{keyword1}%","%#{keyword1}%","%#{keyword1}%") if keyword1.present? }
  scope :range, -> (range) {}
 #scope :メソッド名 -> (引数) { SQL文 }
 #if 引数.present?をつけることで、検索フォームに値がない場合は実行されない
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController

  def twitter
    callback_from :twitter
  end

  def failure
    redirect_to root_path
  end

  private

  # コールバック時に行う処理
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_omniauth(request.env['omniauth.auth'])

    if @user
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except("extra")
      @user = User.new()
      render 'devise/registrations/after_omniauth_signup'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #  super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def mypage
    @user = current_user
    likes = Like.where(user_id: current_user.id).pluck( :post_id)
    @like_list = Post.find(likes)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :birthday, :sex, [:personal_color].to_s, [:skin_quality].to_s, :introduction, :profile_image, :email)
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h3 class="mb-3 fw-normal text-center">Edit User -ユーザー情報編集-</h3>
  <div class="text-center">
    <p class="text-danger">*<span class="small text-muted"> 必須項目です。</span></p>
  </div>

<div class="row justify-content-center">

<%= form_with model: @user, url: user_update_information_path do |f| %>

<table class="table-sm table-borderless">
  <tr>
    <td></td>
    <td></td>
    <th><%= f.file_field :profile_image, placeholder: "profile画像", accept: "image/*" %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td class="col-lg-4"><%= f.label :"ユーザー名" %></td>
    <th class="field col-lg-6"><%= f.text_field :nickname %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td><%= f.label :"生年月日" %></td>
    <th class="field"><%= f.text_field :birthday %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td><%= f.label :"性別" %></td>
    <th class="field"><%= f.select :sex, User.sexes.keys, {prompt: '選択してください'} %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td><%= f.label :"パーソナルカラー" %></td>
    <th class="field"><%= f.select :personal_color, User.personal_colors_i18n.invert.map{|key, value| [key, User.personal_colors[value]]}, {prompt: '選択してください'} %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td><%= f.label :"肌タイプ" %></td>
    <th class="field"><%= f.select :skin_quality, User.skin_qualities_i18n.invert.map{|key, value| [key, User.skin_qualities[value]]}, {prompt: '選択してください'} %></th>
  </tr>
  <tr>
    <td></td>
    <td><%= f.label :"ひとこと" %></td>
    <th class="field"><%= f.text_field :introduction %></th>
  </tr>
  <tr>
    <td><p class="text-danger">*</p></td>
    <td><%= f.label :"メールアドレス" %></td>
    <th class="field"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></th>
  </tr>
</table>

  <div class="actions text-center mt-3 mb-3"><%= f.submit "ユーザー編集", class:"btn-sm btn-info" %></div>
<% end %>

app/views/users/mypage.html.erb
<div class="container">
  <h3 class="mb-3 fw-normal text-center">MyPage -マイページ-</h1>
  <div class="row mb-5">

    <div class="col-lg-6">
      <h4 class="text-dark" style="padding: 1rem 2rem; border: 2px dotted #000;">* Profile *</h4>
      <div><%= image_tag @user.get_profile_image(170,150), class:"rounded-circle" %></div>

      <table class="table-borderless mb-3">
        <tr>
          <th class="col-lg-2">ユーザー名</th>
          <th class="col-lg-4"><%= @user.nickname %></th>
        </tr>
        <tr>
          <th></th>
          <th><%= @user.sex %> / <%= @user.age %>歳</th>
        </tr>
        <tr>
          <th>パーソナルカラー</th>
          <th><%= @user.personal_color_i18n %></th>
        </tr>
        <tr>
          <th>肌タイプ</th>
          <th><%= @user.skin_quality_i18n %></th>
        </tr>
        <tr>
          <th>ひとこと</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <p>
        <%= link_to "ユーザー情報編集", user_edit_information_path, class:"btn-sm btn-info" %>
        <%= link_to "投稿履歴を確認", user_path(@user.id), class:"btn-sm btn-success" %>
      </p>
      <p><%= link_to "退会", confirm_unsubscribe_path, class:"btn-sm btn-dark" %></p>
    </div>

  <div class="col-lg-6">
    <h4 class="text-dark" style="padding: 1rem 2rem; border: 2px dotted #000;">♡ Favorite ♡ -Like!した投稿アイテム-</h4>

    <% if @like_list.present? %>
      <% @like_list.each do |post| %>
      <div class="border mt-3">
        <% post.post_reviews.each do |post_review| %>
          <%= image_tag post_review.get_image, size: "50x50" %>
          <%= link_to post_review.item_name, post_path(post_review.post.id), class:"text-dark" %><br>
        <% end %>
      </div>
      <% end %>
    <% else %>
     <p class="text-center mt-5">まだ　♡ like ボタンを活用していません。<br>
     気になる投稿に　♡like してみましょう♩</p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-lg-5">
      <h5 class="text-dark" style="padding: 1rem 2rem; border: 2px dotted #000;">* Profile *</h5>
      <div><%= image_tag @user.get_profile_image(170,150), class:"rounded-circle" %></div>

      <table class="table-borderless mb-3">
        <tr>
          <th class="col-lg-2">ユーザー名</th>
          <th class="col-lg-3"><%= @user.nickname %></th>
        </tr>
        <tr>
          <th></th>
          <th><%= @user.sex %> / <%= @user.age %>歳</th>
        </tr>
        <tr>
          <th>パーソナルカラー</th>
          <th><%= @user.personal_color_i18n %></th>
        </tr>
        <tr>
          <th>肌タイプ</th>
          <th><%= @user.skin_quality_i18n %></th>
        </tr>
        <tr>
          <th>ひとこと</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
    </div>

<div class="col-lg-7">
<h5 class="text-dark" style="padding: 1rem 2rem; border: 2px dotted #000;"><%= @user.nickname %>'s Reccomend item  -<%= @user.nickname %>の投稿履歴-</h5>

<% @posts.each do |post| %>
<% post.post_reviews.each do |post_review| %>

<table class="table table-borderless">
  <tr>
    <th class="col-lg-1"><%= image_tag post_review.get_image, class:"mini_thumbnail" %></th>
    <td class="col-lg-5">
      <p><%= link_to post_review.item_name, post_path(post_review.post.id) %></p>
      <p><%= post_review.item_genre_i18n %> | <%= post_review.item_brand %></p>
      <%= post.created_at.strftime('%Y/%m/%d') %>
    </td>
    <td class="col-lg-6">
      <span  id="review_star-<%= post_review.id %>"></span>
      <p class="small"><%= post_review.star %>点</p>
      <script>
      $('#review_star-<%= post_review.id %>').raty({
        readOnly: true,
        size     : 5,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        score: <%= post_review.star %>,
        half: true,
      });
      </script>
      <p><%= post_review.good_point %></p>
    </td>
  </tr>
</table>

<% end %>
<% end %>
</div>
</div>

app/views/users/unsubscribe.html.erb
<section class="text-center mt-5 mb-5">
	<h2 class="section-ttl">本当に退会しますか？</h2>
	<h4 class="text-center">退会するとこれまでの履歴が閲覧できなくなります。<br>退会する場合は、「退会する」をクリックしてください。</h4>
	<br>
	<div class="flex justify-around mt2">
		<%= link_to "マイページに戻る", mypage_path(current_user.id), class: "btn-lg btn-primary" %>
		<%= link_to "退会する", withdraw_user_path, method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn-lg btn-danger" %>
	</div>
</section>