config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }

  get '/' => 'homes#top', as: 'root'
  get '/about' => 'homes#about', as: 'about'
  get 'users/mypage' => 'users#mypage', as: 'mypage' do
    get :likes, on: :collection
  end
  get 'users/information/edit' => 'users#edit', as: 'user_edit_information'
  patch 'users/information' => 'users#update', as: 'user_update_information'
  get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  get 'users/:id' => 'users#show', as: 'user'
  get   'contacts'         => 'contacts#index'
  post  'contacts/confirm' => 'contacts#confirm'
  post  'contacts/thanks'  => 'contacts#thanks'
  resources :posts, only: [:new, :create, :show ,:edit, :update,] do
    resource :likes, only: [:create, :destroy]
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => '名前を入力してください'}
  validates :email, :presence => { :message => 'メールアドレスを入力してください'}

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    if @contact.valid?
      render :action => 'confirm'
    else
      render 'index'
    end
  end

  def thanks
    # メール送信
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    ContactMailer.received_email(@contact).deliver
    # 完了画面表示
    render 'thanks'
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="bg-secondary">
<%= form_with model: @contact, url: contacts_thanks_path do |f| %>

<div class="container">
<div class="main container-fluid">
    <div class="row bg-light text-dark py-5">
        <div class="col-md-8 offset-md-2">
            <h2 class="fs-1 mb-5 text-center fw-bold">お問い合わせ内容確認</h2>

  <table class="table">
    <tr>
      <th class="col-md-3">名前</th>
      <td class="col-md-3">
        <%= f.hidden_field :name %><%= @contact.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %><%= @contact.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %><%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
  <div class="text-center"><%= f.submit '送信', :class => 'btn-lg btn-primary' %></div>
<% end %>
</div>
</div>
</div>
</div>

app/views/contacts/index.html.erb
<div class="bg-secondary">
<%= form_with model: @contact, url: contacts_confirm_path do |f| %>

<div class="container">
  <div class="main container-fluid">
    <div class="row bg-light text-dark py-5">
      <div class="col-md-8 offset-md-2">
        <h2 class="fs-1 mb-5 text-center fw-bold">お問い合わせ</h2>

  <% if @contact.errors.any? %>
    <div class="alert alert-danger">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @contact.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th class="col-lg-3">名前<span class="text-danger">（必須）</span></th>
      <td class="col-lg-5"><%= f.text_field :name, class:"form-control" %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email, class:"form-control" %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message, rows: 8, class:"form-control" %></td>
    </tr>
  </table>

  <div class="text-center"><%= f.submit '確 認', class: 'btn-lg btn-primary' %></div>

<% end %>

      </div>
    </div>
  </div>
</div>

app/views/contacts/thanks.html.erb
<div class="text-center mt-5 mb-5">
    <h1>Thank you!</h1>
    <div class="border"><%= image_tag('22623651.jpg', size: '500x350', class:"d-block mx-auto") %></div>
    <p class="mt-5">お問い合わせいただきありがとうございました。</p>
</div>