config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }

  get '/' => 'homes#top', as: 'root'
  get '/about' => 'homes#about', as: 'about'
  get 'users/mypage' => 'users#mypage', as: 'mypage' do
    get :likes, on: :collection
  end
  get 'users/information/edit' => 'users#edit', as: 'user_edit_information'
  patch 'users/information' => 'users#update', as: 'user_update_information'
  get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  get 'users/:id' => 'users#show', as: 'user'
  get   'contacts'         => 'contacts#index'
  post  'contacts/confirm' => 'contacts#confirm'
  post  'contacts/thanks'  => 'contacts#thanks'
  resources :posts, only: [:new, :create, :show ,:edit, :update,] do
    resource :likes, only: [:create, :destroy]
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosmeBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/d0ba5b4acd.js" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <header class="shadow-sm">

    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><%= image_tag asset_path('logo.png'), size: '150x150' %></a>

        <div>
          <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "マイページ", mypage_path, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "問い合わせ", contacts_path, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "投稿する", new_post_path, class: 'nav-link text-white btn-info' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
            <li class="nav-item"><%= link_to "問い合わせ", contacts_path, class: 'nav-link text-dark' %></li>
          <% end %>
          </ul>
        </div>

        <div class="navbar-nav">
        <% if user_signed_in? %>
          <div class="search_form border p-1 col-log-8">
            <div class="user-search mb-1">
            <%= form_with(scope: :search, url: search_path, method: :get, local: true) do |fs| %>
              <%= fs.hidden_field :range, :value => "User" %>
              <%= fs.label :"パーソナルカラー", class:"small" %>
              <%= fs.select :personal_color, User.personal_colors_i18n.invert.map{|key, value| [key, User.personal_colors[value]]}, include_blank: true, class:"small" %>
              <%= fs.label :" 肌タイプ", class:"small" %>
              <%= fs.select :skin_quality, User.skin_qualities_i18n.invert.map{|key, value| [key, User.skin_qualities[value]]}, include_blank: true, class:"small" %><br>
              <div class="text-right">
              <i class="fas fa-search"></i>
              <%= fs.text_field :keyword1, :placeholder =>"キーワードで検索", class:"small" %>
              <%= fs.submit "ユーザー検索", class:"btn-sm btn-secondary " %>
              </div>
            <% end %>
            </div>
            <div class="item-search">
              <%= form_with(scope: :search, url: search_path, method: :get, local: true) do |f| %>
                <%= f.hidden_field :range, :value => "PostReview" %>
                <%= f.label :"カテゴリ", class:"small" %>
                <%= f.select :item_genre, PostReview.item_genres_i18n.invert.map{|key, value| [key, PostReview.item_genres[value]]}, include_blank: true, class:"small" %>
                <i class="fas fa-search"> </i><%= f.text_field :keyword2, :placeholder =>"キーワードで検索", class:"small" %><br>
                <div class="text-right"><%= f.submit "アイテム検索", class:"btn-sm btn-secondary text-right" %></div>
              <% end %>
            </div>
          </div>
        <% else %>
          <p class="border p-3 text-center text-info">会員登録をすれば検索機能も使用可能♩<br>ぜひ会員登録を！</p>
        <% end %>
        </div>

      </div>
    </nav>
    </header>

  <main>
    <%= yield %>
  </main>

  <footer class="bg-dark fixed-bottom">
  　<p class="text-light text-center">＼ COSME makes you HAPPY ♡ ／</p>
  </footer>

  </body>
</html>